version: '3'
services:
  api:
    container_name: api
    build:
      context: .././
      dockerfile: ./dockerfiles/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ../:/go/src/app
    ports:
      - 8081:8081
    environment:
      POSTGRES_USER: "linebot"
      POSTGRES_PASSWORD: "linebot_password"
      POSTGRES_DB: "linebot"
      DB_HOSTNAME: "linebot_db"
      PORT: "8081"
    networks:
      - db-api-network


  db:
    image: postgres:latest
    container_name: linebot_db
    restart: always
    environment:
      POSTGRES_USER: "linebot"
      POSTGRES_PASSWORD: "linebot_password"
      POSTGRES_DB: "linebot"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: 'Asia/Tokyo'
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - db-api-network

networks:
  db-api-network:
    external: true
